namespace com.github.hummel.mpp.lab5;

#pragma warning disable CS8618

public class HelperClassForCommon : ITestInterface
{
    public readonly string shouldNotBeEmpty = "";
    public readonly string shouldBeEmpty = "";
    public readonly string autoGenerated = "";
    public readonly INestedInterface nested;

    public HelperClassForCommon()
    {
    }

    [ConstructorAnnotation]
    public HelperClassForCommon(
        [ParameterAnnotation("Impl2")] INestedInterface nested,
        string shouldNotBeEmpty,
        string autoGenerated
    )
    {
        this.nested = nested;
        this.autoGenerated = autoGenerated;
        this.shouldNotBeEmpty = shouldNotBeEmpty;
    }
}

public class Impl1 : INestedInterface
{
    [ConstructorAnnotation]
    public Impl1()
    {
    }
}

public class Impl2 : INestedInterface
{
    [ConstructorAnnotation]
    public Impl2()
    {
    }
}

public class Impl3 : IDoubleNestedInterface
{
    [ConstructorAnnotation]
    public Impl3()
    {
    }
}

public interface ITestInterface
{
}

public interface INestedInterface
{
}

public interface IDoubleNestedInterface
{
}