namespace com.github.hummel.mpp.lab5;

using FluentAssertions;
using NUnit.Framework;

public class CommonCreatingTest
{
    HelperClassForCommon instance;

    [OneTimeSetUp]
    public void initialize()
    {
        var depConfig = new DependenciesConfiguration();
        depConfig.register<ITestInterface, HelperClassForCommon>(
            parameters: new DependencyParameter("parameter", "Tested")
        );
        depConfig.register<INestedInterface, Impl1>();
        depConfig.register<INestedInterface, Impl2>(name: "Impl2");
        depConfig.register<IDoubleNestedInterface, Impl3>();
        var provider = new DependencyProvider(depConfig);
        instance = (HelperClassForCommon)provider.resolve<ITestInterface>();
    }

    [Test]
    public void dependencyConstructorTest()
    {
        instance.shouldNotBeEmpty.Should().NotBeEmpty();
        instance.shouldBeEmpty.Should().Be("");
        instance.autoGenerated.Should().NotBeEmpty();
    }

    [Test]
    public void dependencyNestedTest()
    {
        instance.nested.Should().BeOfType<Impl2>();
    }
}