name: .NET
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ 'Lab1', 'Lab2', 'Lab3', 'Lab4' ]
    steps:
    - uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./app${{matrix.version}}
      run: dotnet restore
    - name: Build
      working-directory: ./app${{matrix.version}}
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./app${{matrix.version}}
      run: dotnet test --no-build --verbosity normal
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: compiled-artifact
        path: |
          ./app${{matrix.version}}/bin/Debug/net8.0/*.exe
          ./app${{matrix.version}}/bin/Debug/net8.0/*.dll
