name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd appLab1
        npm ci
    - name: Build project
      run: |
        cd appLab1
        npm run build --if-present
    - name: Run tests
      run: |
        cd appLab1
        npm test
