name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ 'Lab1' ]
    steps:
    - run: npm ci
      working-directory: ${{matrix.version}}
    - run: npm run build --if-present
      working-directory: ${{matrix.version}}
    - run: npm test
      working-directory: ${{matrix.version}}
